apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-orchestrator
  labels:
    app: bot-orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bot-orchestrator
  template:
    metadata:
      labels:
        app: bot-orchestrator
    spec:
      serviceAccountName: bot-orchestrator-sa
      containers:
      - name: bot-orchestrator
        image: bot-orchestrator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: API_BASE_URL
          value: "http://api-service:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bot-orchestrator-service
spec:
  selector:
    app: bot-orchestrator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
